# Tensorflow practice

link: http://tensorflow.org
link: http://learningtensorflow.com/lesson2/

This will be my learning notebook for tensorflow

In [5]:
#Hello World for tensorflow
import tensorflow as tf
hello = tf.constant('Hello World!')
with tf.Session() as sess:
    print(sess.run(hello))

Hello World!


In [6]:
#Gives out a tensor information not the answer we want
x = tf.constant(35, name='x')
y = tf.Variable(x+5, name='y')
print(y)

Process:
1. Import the tensorflow module and call it tf
2. Create a constant value called x, and give it the numerical value 35
3. Create a variable called y, and define it as being the equation x + 5
4. Print out the equation object for y

In [7]:
#Working the right way
x = tf.constant(35, name='x')
y = tf.Variable(x+5, name='y')

model = tf.initialize_all_variables()

with tf.Session() as sess:
    sess.run(model)
    print(sess.run(y))

40


In [8]:
x = tf.constant([35, 40, 45], name='x')
y = tf.Variable(x+5, name='y')

#initialize all variables
model = tf.initialize_all_variables()

#create session
with tf.Session() as sess:
    #run model that initializes all variables
    sess.run(model)
    print(sess.run(y))

[40 45 50]


In [8]:
import tensorflow as tf

x =  tf.Variable(0, name='x')

model = tf.initialize_all_variables()

with tf.Session() as sess:
    #we only need to run the model that 
    #initializes all variabes pnes
    sess.run(model)
    
    #iterate 5 times adding 1 to x
    for i in range(5):
        x = x + 1
        print(sess.run(x))


1
2
3
4
5


In [9]:
import tensorflow as tf

x = tf.constant(35,name='x')
print(x)
y = tf.Variable(x+5, name='y')

with tf.Session() as sess:
    merged = tf.merge_all_summaries()
    writer = tf.train.SummaryWriter("/tmp/basic", sess.graph)
    model = tf.initialize_all_variables()
    sess.run(model)
    print(sess.run(y))

Tensor("x_3:0", shape=(), dtype=int32)
40


# Lesson 3

 ![title](MarshOrchid.jpg)

In [1]:
import matplotlib.image as mpimg


filename = "MarshOrchid.jpg"
image = mpimg.imread(filename)

print(image.shape)
# % matplotlib inline

(5528, 3685, 3)


Geometric Manipulations

- Turning the image 90 degrees

In [2]:
import tensorflow as tf
import matplotlib.image as mpimg
import matplotlib.pyplot as plt

filename ="MarshOrchid.jpg"
image = mpimg.imread(filename)

x = tf.Variable(image, name='x')

model = tf.initialize_all_variables()

with tf.Session() as sess:
    x = tf.transpose(x, perm = [1,0,2])
    sess.run(model)
    result = sess.run(x)
    
plt.imshow(result)
plt.show()

Flip image

In [3]:
import numpy as np
import tensorflow as tf
import matplotlib.image as mpimg
import matplotlib.pyplot as plt

filename = "MarshOrchid.jpg"
image = mpimg.imread(filename)
height, width, depth = image.shape

x = tf.Variable(image, name='x')
model = tf.initialize_all_variables()

with tf.Session() as session:
    x = tf.reverse_sequence(x, np.ones((height,))*width
                            , 1, batch_dim=0)
    session.run(model)
    result = session.run(x)

print(result.shape)
plt.imshow(result)
plt.show()

(5528, 3685, 3)


# Lesson 4

Placeholders
     - A placeholder is simply a variable that we will assign data to at a later date.

In [5]:
import tensorflow as tf

#tf.placeholder initializes a tensor even without
#anything in it.
#'float' specifies the data type
# 3 specifies the shape of the tensor
x = tf.placeholder('float',3)
y = x*2

with tf.Session() as sess:
    result = sess.run(y, feed_dict={x: [1,2,3]})
    print(result)

Tensor("mul_1:0", shape=(3,), dtype=float32)
[ 2.  4.  6.]


In [7]:
import tensorflow as tf

#x now has a shape of [None, 3]
#None states that of any value for row
#3 states that there must always be 3 values for column
x = tf.placeholder('float',[None, 3])
y = x*2

with tf.Session() as sess:
    x_data = [[1,2,3],
              [4,5,6]]
    result = sess.run(y, feed_dict={x:x_data})
    print(result)

[[  2.   4.   6.]
 [  8.  10.  12.]]


In [8]:
import tensorflow as tf
import matplotlib.image as mpimg
import matplotlib.pyplot as plt

filename = 'MarshOrchid.jpg'
raw_image_data = mpimg.imread(filename)

#Create a tf.placeholder with the shape of [None, None, 3]
#No limits for x and y with 3 as depth for RGB
image = tf.placeholder('uint8', [None,None,3])

#Create a tf.slice that takes the parameters
#(input_, beginning, size)
#-1 implies the last part a pythonic way of saying last
slice = tf.slice(image, [1000,0,0], [3000, -1, -1])

with tf.Session() as sess:
    result = sess.run(slice, feed_dict={image:raw_image_data})
    print(result.shape)
    
plt.imshow(result)
plt.show()

(3000, 3685, 3)


# Exercise

split the picture to 4 corners

In [13]:
import tensorflow as tf
import matplotlib.image as mpimg
import matplotlib.pyplot as plt

filename ='MarshOrchid.jpg'
raw_image_data = mpimg.imread(filename)

#create a tf.placeholder that will contain all the images
upper_left = tf.placeholder('uint8', [None, None, 3])
lower_left = tf.placeholder('uint8', [None, None, 3])
upper_right = tf.placeholder('uint8', [None, None, 3])
lower_right = tf.placeholder('uint8', [None, None, 3])

#Set the correct slice for the image
#the target is to create 4 different images from the main image
#using four corners
slice_upper_left = tf.slice(upper_left, [0,0,0], [2764, 1842,-1])
slice_lower_left = tf.slice(lower_left, [2764,0,0], [2764, 1842, -1])
slice_upper_right = tf.slice(upper_right, [0,1842,0], [2764, 1842, -1])
slice_lower_right = tf.slice(lower_right, [2764,1842,0],[2764, 1842, -1])



#Create a session object named sess
with tf.Session() as sess:
    #run the tf.slice then feed the data using feed_dict
    #data needed is the image
    uleft = sess.run(slice_upper_left, feed_dict={upper_left:raw_image_data})
    lleft = sess.run(slice_lower_left, feed_dict={lower_left:raw_image_data})
    uright = sess.run(slice_upper_right, feed_dict={upper_right:raw_image_data})
    lright = sess.run(slice_lower_right, feed_dict={lower_right:raw_image_data})
    print(uleft.shape)
    print(lleft.shape)
    print(uright.shape)
    print(lright.shape)

#Using matplotlib plot all the images
plt.subplot(221)    
plt.imshow(uleft)

plt.subplot(222)
plt.imshow(uright)

plt.subplot(223)
plt.imshow(lleft)

plt.subplot(224)
plt.imshow(lright)

plt.show()

(2764, 1842, 3)
(2764, 1842, 3)
(2764, 1842, 3)
(2764, 1842, 3)


# Lesson 5

Iteration

In [14]:
import tensorflow as tf

#interactiveSession for a one call instance of the
#session, the con for this is we must close the session
#every time at the last part
session = tf.InteractiveSession()
x = tf.constant(list(range(10)))
print(x.eval())
session.close()

[0 1 2 3 4 5 6 7 8 9]


In [19]:
#know how may memory a python session is using
import resource
print('{} Kb' .format(resource.getrusage(resource.RUSAGE_SELF).ru_maxrss) )

2857916 Kb


In [20]:
import numpy as np
session = tf.InteractiveSession()

X = tf.constant(np.eye(10000))
Y = tf.constant(np.random.randn(10000,300))
Z = tf.matmul(X,Y)


Exception AssertionError: AssertionError() in <bound method InteractiveSession.__del__ of <tensorflow.python.client.session.InteractiveSession object at 0x7fdc64d1d310>> ignored


# Lesson 6

- create a fake data mining algorithm using kmeans.

In [5]:
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt


def create_samples(n_clusters, n_samples_per_cluster, n_features, embiggen_factor, seed):
    """
    n_clusters = number of clusters that we will ambiguously create
    n_samples_per_cluster = how many points are grouped together to form the cluster
    n_features = 
    embiggen_factor = 
    seed = 
    """
    np.random.seed(seed)
    slices = []
    centroids = []

    for i in range (n_clusters):
        samples = tf.random_normal((n_samples_per_cluster, n_features), mean=0.0, stddev=5.0, dtype=tf.float32,
                                   seed=seed, name="cluster_{}".format(i))
        """
        stddev = standard eviation
        dtype = data type
        """
        current_centroid = (np.random.random((1, n_features))*embiggen_factor) - (embiggen_factor/2)
        centroids.append(current_centroid)
        samples += current_centroid
        slices.append(samples)

    #Add all information to the samples and centroid
    samples = tf.concat(0, slices, name='samples')
    centroids = tf.concat(0, centroids, name='centroids')
    return centroids, samples

def plot_clusters(all_samples, centroids, n_samples_per_cluster):

    colour = plt.cm.rainbow(np.linspace(0, 1, len(centroids)))
    for i, centroid in enumerate(centroids):
        samples = all_samples[i*n_samples_per_cluster:(i+1)*n_samples_per_cluster]
        plt.scatter(samples[:,0], samples[:,1], c=colour[i])
        plt.plot(centroid[0], centroid[1], markersize=35, marker='x', color='k', mew=10)
        plt.plot(centroid[0], centroid[1], markersize=30, marker='x', color='m', mew=5)

    plt.show()



In [6]:
import tensorflow as tf
import numpy as np
from km import create_samples, plot_clusters
n_features = 2
n_clusters = 3
n_samples_per_clusters = 500
seed = 700
embiggen_factor = 70

np.random.seed(seed)
centroids, samples = create_samples(n_clusters, n_samples_per_clusters, n_features, embiggen_factor, seed)

model = tf.initialize_all_variables()
with tf.Session() as sess:
    samples_values = sess.run(samples)
    centroid_values = sess.run(centroids)
    plot_clusters(samples_values, centroid_values, n_samples_per_clusters)


 # Lesson 7
 
 -working on loops

In [8]:
#import tensorflow
import tensorflow as tf

#create a tensor variable that holds 0 with the name x
x = tf.Variable(0., name='x')

#create a tensor constant that holds a float 5.
threshold = tf.constant(5.)

#Initialize all variable for the Session()
model = tf.initialize_all_variables()

#Start the session as sess, we can pass by sess.close()
#using with
with tf.Session() as sess:
    
    #run model, which initializes all variables
    #and constants
    sess.run(model)
    
    #create a while loop that checks if the value of x is still less than the value of threshold
    while sess.run(tf.less(x, threshold)):
        x = x + 1
        x_value = sess.run(x)
        print(x_value)

1.0
2.0
3.0
4.0
5.0


# Gradient Descent

- further explanation

In [10]:
import tensorflow as tf
import numpy as np

x = tf.placeholder('float')
y = tf.placeholder('float')

w = tf.Variable([1.0, 2.0], name='w')

#Model => y = mx + b
#where:
#m = weight
#b = bias
#x = different features
y_model = tf.mul(x, w[0])+w[1]

error = tf.square(y-y_model)
train_op = tf.train.GradientDescentOptimizer(0.01).minimize(error)
model = tf.initialize_all_variables()

with tf.Session() as sess:
    sess.run(model)
    for i in range(1000):
        x_value = np.random.rand()
        y_value = x_value * 2 + 6
        sess.run(train_op, feed_dict={x: x_value, y: y_value})
        
    w_value = sess.run(w)
    print("Predicted Model: {a:.3f}x + {b:.3f}".format(a=w_value[0], b=w_value[1]))
    

Predicted Model: 2.283x + 5.855


# Predicted Model

- predicted model = 2.283x + 5.855
- m = 2.283 ==> weight
- b = 5.855 ==> bias

In [7]:
import tensorflow as tf
import numpy as np

x = tf.placeholder('float')
y = tf.placeholder('float')

w = tf.Variable([1.0, 2.0], name='w')

#Model => y = mx + b
#where:
#m = weight
#b = bias
#x = different features
y_model = tf.mul(x, w[0])+w[1]

error = tf.square(y-y_model)
train_op = tf.train.GradientDescentOptimizer(0.01).minimize(error)
model = tf.initialize_all_variables()
errors = []

with tf.Session() as sess:
    sess.run(model)
    for i in range(1000):
        x_train = tf.random_normal((1,), mean=5, stddev=2.0)
        y_train = x_train * 2 + 6
        x_value, y_value = sess.run([x_train, y_train])
        _, error_value = sess.run([train_op, error], feed_dict={x:x_value, y:y_value})
        errors.append(error_value)   
    w_value = sess.run(w)
    print("Predicted Model: {a:.3f}x + {b:.3f}".format(a=w_value[0], b=w_value[1]))

import matplotlib.pyplot as plt
plt.plot([np.mean(errors[i-50:i]) for i in range(len(errors))])
# %matplotlib inline
plt.show()
# plt.savefig("errors.png")

Predicted Model: 2.055x + 5.713


/home/fjcamillo/anaconda2/envs/tensorflow/lib/python2.7/site-packages/numpy/core/_methods.py:59: RuntimeWarning: Mean of empty slice.
  warnings.warn("Mean of empty slice.", RuntimeWarning)


# Lesson 8

- custom functions with the game of life

### Game of Life 

- is a small life representation game using pixels

Rules:

1. Over population
2. Stasis
3. Under population
4. Reproduction

In [1]:
import tensorflow as tf
import matplotlib.pyplot as plt

#We createed a square of size 50
shape = (50,50)

#Create a randomized tensor with 1's and 0's
initial_board = tf.random_uniform(shape, minval=0, maxval=2, dtype=tf.int32)

#create a session as sess
with tf.Session() as sess:
    x = sess.run(initial_board)

#plot the information
fig = plt.figure()
plot = plt.imshow(x, cmap='Greys', interpolation='nearest')
plt.show()

In [3]:
import numpy as np
from scipy.signal import convolve2d
import matplotlib.animation as animation
import matplotlib.pyplot as plt
shape = (50,50)
initial_board = tf.random_uniform(shape, minval=0, maxval=2, dtype=tf.int32)

def update_board(X):
    N = convolve2d(X, np.ones((3,3)), mode = 'same', boundary='wrap') - X
    X = (N==3)|(X & (N==2))
    return X

board = tf.placeholder(tf.int32, shape=shape, name='board')

#turns a python function into a neural network node
board_update = tf.py_func(update_board, [board], [tf.int32])

with tf. Session() as sess:
    initial_board_values = sess.run(initial_board)
    X = sess.run(board_update, feed_dict={board: initial_board_values})[0]
    
    def game_of_life(*args):
        X = sess.run(board_update, feed_dict={board: X})[0]
        plot.set_array(X)
        return plot,
    
    fig = plt.figure()

    ani = animation.FuncAnimation(fig, game_of_life, interval=200, blit=True)
#     plot = plt.imshow(X, cmap='Greys', interpolation='nearest')
    plt.show()

UnboundLocalError: local variable 'X' referenced before assignment

UnboundLocalError: local variable 'X' referenced before assignment

# Lesson 9

-Tensorflow Learn (skflow)

In [4]:
from sklearn.datasets import load_digits
from matplotlib import pyplot as plt

digits = load_digits()

fig = plt.figure(figsize=(3,3))

plt.imshow(digits['images'][66], cmap='gray', interpolation='none')
plt.show()

In [40]:
from tensorflow.contrib import skflow
import tensorflow as tf
import numpy as np
import pandas as pd
from sklearn.metrics import accuracy_score

X_train_run = pd.DataFrame([[130, 25, 50],
               [160, 12, 25],
               [150, 17, 12],
               [158, 15, 4]])
y_train_run = pd.DataFrame([[1],[0],[0],[1]])
X_test_run = pd.DataFrame([[145,20,20],
                           [150,25,12],
                           [146, 13, 15], 
                           [99, 21, 12]])

y_test_run = pd.DataFrame([[1],[1],[1],[1]])

classifier = skflow.TensorFlowDNNClassifier(hidden_units=[10,20,10], n_classes=5, learning_rate=0.001 )
classifier.fit(X_train_run, y_train_run)
y_pred = classifier.predict(X_test_run)
print(y_pred)
print(accuracy_score(y_test_run, y_pred))

Step #100, epoch #100, avg. train loss: 27.35069
Step #200, epoch #200, avg. train loss: 14.69771
[1 1 1 1]
1.0


In [4]:
import tensorflow.contrib.learn as skflow
from sklearn import datasets, metrics

iris = datasets.load_iris()
print(iris)
classifier = skflow.TensorFlowDNNClassifier(hidden_units=[10, 20, 10, 20], n_classes=10)
classifier.fit(iris.data, iris.target)
score = metrics.accuracy_score(iris.target, classifier.predict(iris.data))
print("Accuracy: %f" % score)

{'target_names': array(['setosa', 'versicolor', 'virginica'], 
      dtype='|S10'), 'data': array([[ 5.1,  3.5,  1.4,  0.2],
       [ 4.9,  3. ,  1.4,  0.2],
       [ 4.7,  3.2,  1.3,  0.2],
       [ 4.6,  3.1,  1.5,  0.2],
       [ 5. ,  3.6,  1.4,  0.2],
       [ 5.4,  3.9,  1.7,  0.4],
       [ 4.6,  3.4,  1.4,  0.3],
       [ 5. ,  3.4,  1.5,  0.2],
       [ 4.4,  2.9,  1.4,  0.2],
       [ 4.9,  3.1,  1.5,  0.1],
       [ 5.4,  3.7,  1.5,  0.2],
       [ 4.8,  3.4,  1.6,  0.2],
       [ 4.8,  3. ,  1.4,  0.1],
       [ 4.3,  3. ,  1.1,  0.1],
       [ 5.8,  4. ,  1.2,  0.2],
       [ 5.7,  4.4,  1.5,  0.4],
       [ 5.4,  3.9,  1.3,  0.4],
       [ 5.1,  3.5,  1.4,  0.3],
       [ 5.7,  3.8,  1.7,  0.3],
       [ 5.1,  3.8,  1.5,  0.3],
       [ 5.4,  3.4,  1.7,  0.2],
       [ 5.1,  3.7,  1.5,  0.4],
       [ 4.6,  3.6,  1. ,  0.2],
       [ 5.1,  3.3,  1.7,  0.5],
       [ 4.8,  3.4,  1.9,  0.2],
       [ 5. ,  3. ,  1.6,  0.2],
       [ 5. ,  3.4,  1.6,  0.4],
       [ 5.2,  3.

In [41]:
from sklearn.tree import DecisionTreeClassifier

X = [[150, 25], [175, 12]]
y = [1,0]
x_test = [[145, 20],[125, 15]]
y_test = [1,0]
clf = DecisionTreeClassifier()
clf.fit(X, y)
pred = clf.predict(x_test)
print(pred)
accuracy_score(y_test, pred)

[1 1]


0.5